[[breaking]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_vpc_router_route` [#423](https://github.com/oxidecomputer/terraform-provider-oxide/pull/423)."

[[features]]
title = "New data resource"
description = "`oxide_vpc_router_route` [#423](https://github.com/oxidecomputer/terraform-provider-oxide/pull/423)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""
