[[breaking]]
title = "Minimum Terraform version v1.11 required"
description = "Due to the introduction of [write-only attributes](https://developer.hashicorp.com/terraform/plugin/framework/resources/write-only-arguments) in the new `oxide_silo` resoucre, the minimum Terraform version is now v1.11 [#425](https://github.com/oxidecomputer/terraform-provider-oxide/pull/425)."

[[features]]
title = "New resource"
description = "`oxide_silo` [#425](https://github.com/oxidecomputer/terraform-provider-oxide/pull/425)."

[[features]]
title = "New data resource"
description = "`oxide_vpc_router_route` [#423](https://github.com/oxidecomputer/terraform-provider-oxide/pull/423)."

[[enhancements]]
title = "VPC firewall rules resource"
description = "In place updates are now supported [#432](https://github.com/oxidecomputer/terraform-provider-oxide/pull/432)"

[[bugs]]
title = ""
description = ""
