[[breaking]]
title = "`oxide_vpc_firewall_rules`"
description = "Updated the schema for the `protocols` attribute to allow for more control over ICMP traffic. [#474](https://github.com/oxidecomputer/terraform-provider-oxide/pull/474)"

[[features]]
title = ""
description = ""

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""
