[[breaking]]
title = "`oxide_vpc_firewall_rules`"
description = "Updated the schema for the `protocols` attribute to allow for more control over ICMP traffic. [#474](https://github.com/oxidecomputer/terraform-provider-oxide/pull/474)"

[[features]]
title = ""
description = ""

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = "`oxide_instance`"
description = "Fixed a provider crash when applying a configuration with an empty `boot_disk_id` attribute and a non-empty `disk_attachments` attribute. [#471](https://github.com/oxidecomputer/terraform-provider-oxide/pull/471)"
