[[breaking]]
title = ""
description = ""

[[features]]
title = "New data source"
description = "`oxide_system_ip_pool`"

[[features]]
title = "New resource"
description = "Added the `oxide_system_ip_pool_silo_link` resource and deprecated `oxide_ip_pool_silo_link` in its favor."

[[enhancements]]
title = "`oxide_silo_saml_identity_provider`"
description = "The `idp_metadata_source` and `signing_keypair.private_key` attributes are now write-only. [#819](https://github.com/oxidecomputer/terraform-provider-oxide/pull/819)"

[[enhancements]]
title = "`oxide_silo_saml_identity_provider`"
description = "The `oxide_silo_saml_identity_provider` resource can now be imported. [#819](https://github.com/oxidecomputer/terraform-provider-oxide/pull/819)"

[[bugs]]
title = ""
description = ""
