[[breaking]]
title = ""
description = ""

[[features]]
title = "New data source"
description = "`oxide_system_ip_pool`"

[[features]]
title = "New data source"
description = "`oxide_system_subnet_pools`"

[[features]]
title = "New data source"
description = "`oxide_current_user`"

[[enhancements]]
title = "`oxide_instance`"
description = "The oxide_instance resource now exposes a read-only `attached_external_ips` attribute, which lists attached floating, ephemeral, and SNAT external IP addresses. For Terraform-managed instances, this attribute can replace the `oxide_instance_external_ips` data source. [#841](https://github.com/oxidecomputer/terraform-provider-oxide/pull/841)"

[[enhancements]]
title = "`oxide_silo_saml_identity_provider`"
description = "The `idp_metadata_source` and `signing_keypair.private_key` attributes are now write-only. [#819](https://github.com/oxidecomputer/terraform-provider-oxide/pull/819)"

[[enhancements]]
title = "`oxide_silo_saml_identity_provider`"
description = "The `oxide_silo_saml_identity_provider` resource can now be imported. [#819](https://github.com/oxidecomputer/terraform-provider-oxide/pull/819)"

[[bugs]]
title = "`oxide_instance`"
description = "Previously, the provider would fail to detect a diff on the `external_ips` attribute of the `oxide_instance` resource when external IPs were detached from the instance out of band. These diffs are now detected correctly. [#842](https://github.com/oxidecomputer/terraform-provider-oxide/pull/842)"
