[[breaking]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_ip_pool_silo_link` [#345](https://github.com/oxidecomputer/terraform-provider-oxide/pull/345)"

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""