[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[enhancements]]
title = "Instance resource"
description = "Updates to `Memory` and `NCPUs` no longer require resource replace [#370](https://github.com/oxidecomputer/terraform-provider-oxide/pull/370)."

[[bugs]]
title = ""
description = ""