[[breaking]]
title = ""
description = ""

[[features]]
title = ""
description = ""

[[enhancements]]
title = "Instance resource"
description = "Updates to `Memory` and `NCPUs` no longer require resource replace [#XXX](https://github.com/oxidecomputer/terraform-provider-oxide/pull/XXX)."

[[bugs]]
title = ""
description = ""