[[breaking]]
title = ""
description = ""

[[features]]
title = "Profile Argument for Terraform Provider"
description = "Allows authentication via a authenticated `profile` in `credentials.toml` [#383](https://github.com/oxidecomputer/terraform-provider-oxide/pull/383)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_vpc_internet_gateway` [#389](https://github.com/oxidecomputer/terraform-provider-oxide/pull/389)."

[[features]]
title = "New datasource"
description = "`oxide_vpc_internet_gateway` [#389](https://github.com/oxidecomputer/terraform-provider-oxide/pull/389)."