[[breaking]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_silo` [#389](https://github.com/oxidecomputer/terraform-provider-oxide/pull/407)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""