[[breaking]]
title = ""
description = ""

[[features]]
title = "Adding oxide_silo resource"
description = "Adding the oxide_silo resource for Silo CRUD. This allows for an oxide_silo resource to be managed through Terraform."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""