[[breaking]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_floating_ip` [#427](https://github.com/oxidecomputer/terraform-provider-oxide/pull/427)."

[[features]]
title = "New data resource"
description = "`oxide_floating_ip` [#427](https://github.com/oxidecomputer/terraform-provider-oxide/pull/427)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""
