---
version: "2"

linters:
  default: standard
  enable:
    - godoclint
    - unparam
    - goheader
  disable:
    - errcheck
  settings:
    godoclint:
      default-rule-set: basic
      rules:
        - max-len
      options:
        max-len:
          length: 100
    goheader:
      template: |-
        This Source Code Form is subject to the terms of the Mozilla Public
        License, v. 2.0. If a copy of the MPL was not distributed with this
        file, You can obtain one at https://mozilla.org/MPL/2.0/.

formatters:
  enable:
    - goimports
    - golines
  settings:
    golines:
      max-len: 100
      shorten-comments: true
    goimports:
      local-prefixes:
        - github.com/oxidecomputer/terraform-provider-oxide
  exclusions:
    generated: disable

run:
  timeout: 5m
